apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: bkclangkd-go 
  janus-idp.io/tekton: bkclangkd-go
  backstage.io/kubernetes-id: bkclangkd-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bkclangkd-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  